apiVersion: v1
kind: Secret
metadata:
  name: session-secret
type: Opaque
stringData:
  SESSION_SECRET: my_secret

---

apiVersion: v1
kind: Secret
metadata:
  name: stripe-secret
type: Opaque
stringData:
  STRIPE_PRIVATE_KEY: my_private_key

---

apiVersion: v1
kind: Secret
metadata:
  name: admin-secret
type: Opaque
stringData:
  ADMIN_EMAIL: your_santhoshramesh1020@gmail.com
  ADMIN_PASSWORD: admin_pass
  ADMIN_COOKIE_NAME: cookie_name
  ADMIN_COOKIE_PASSWORD: cookie_pass
